<?php
		$params = Mage::app()->getRequest()->getParams();
		if (isset($params['secureHash'])) {
			$securehash = $params['secureHash'];	
		}
		if (isset($params['email'])) {
			$email = $params['email'];	
		}
		$isUser = $this->checkUserData();
		//echo $isUser;
		if($isUser == true) {
?>
			<div class="page-title">
				<h1>
					<?php echo $this->__('Change your password here') ?>
				</h1>
			</div>
			<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
			<?php 
				$newUrl = Mage::getBaseUrl();
        		$newUrl .= 'securepassword/request/editpost'; 
        	?>
			
			<form id="changePasswordSecure" method="post" action="<?php echo $newUrl ?>">
				<?php if (isset($params['secureHash'])): ?>
					<input type="hidden" name="secureHash" id="secureHash" value="<?php echo $securehash ?>">
				<?php endif; ?>
				<?php if (isset($params['email'])): ?>
					<input type="hidden" name="email" id="email" value="<?php //echo $email ?>">
				<?php endif; ?>
				<div class="fieldset">
					<h2 class="legend">
						<?php echo $this->__('Change Password') ?>
					</h2>
					<ul class="form-list">
						<li class="fields">
							<div class="field">
								<label class="required" for="password">
									<em>*</em>
									<?php echo $this->__('New Password') ?>
								</label>
								<div class="input-box">
									<input id="password" class="input-text validate-password required-entry" type="password" name="password" title="New Password">
								</div>
							</div>
							<div class="field">
								<label class="required" for="confirmation">
									<em>*</em>
									<?php echo $this->__('Confirm New Password') ?>
								</label>
								<div class="input-box">
									<input id="confirmation" class="input-text validate-cpassword required-entry" type="password" name="confirmation" title="Confirm New Password">
								</div>
							</div>
						</li>
					</ul>
				</div>
				<div class="buttons-set">
					<p class="required">
						<?php echo $this->__('* Required Fields') ?>
					</p>
					<button class="button" title="<?php echo $this->__('Save'); ?>" type="submit">
						<span>
							<span>
								<?php echo $this->__('Save') ?>
							</span>
						</span>
					</button>
				</div>
			</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('changePasswordSecure', true);
//]]>
</script>
<?php } 
		else 
		{ 
			echo $isUser;
		}